name: Validate Pull Request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew clean build

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: pull-request-${{ github.event.pull_request.number }}
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 7
